name: softmint_plugin_example
description: "Demonstrates how to use the softmint_plugin plugin."
publish_to: 'none' 
version: 0.1.0
environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  softmint_plugin:
    path: ../
  cupertino_icons: ^1.0.8
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true