name: softmint_plugin
description: "A new Flutter plugin project."
version: 0.0.1
# homepage:
environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  plugin_platform_interface: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.example.softmint_plugin
        pluginClass: SoftmintPlugin
      ios:
        pluginClass: SoftmintPlugin
      linux:
        pluginClass: SoftmintPlugin
      macos:
        pluginClass: SoftmintPlugin
      windows:
        pluginClass: SoftmintPluginCApi
      web:
        pluginClass: SoftmintPluginWeb
        fileName: softmint_plugin_web.dart